### ISSUE TITLE
Hello I ask you to give me credits as this plugin is mine if not ill be forced to take it down with a DMCA

### ISSUE THREAD

**Issue by BajanVlogs** [StrafelessPvP/Genbuckets-PATCH#1]

**Comment by StrafelessPvP** [comment]
You are not the developer of GenBuckets, CortexPE is the developer of GenBuckets which i would give him credits soon, If i see you claiming work that is not yours BajanVlogs i will have no choice to take it to the DMCA

**Comment by BajanVlogs** [comment]
CortexPE made it for me I edited the whole plugin as it didn't work for 1.2 so ill do u a favour ill submit a dmca takedown

**Comment by StrafelessPvP** [comment]
You can go ahead BajanVlogs; CortexPE clearly has his name on the plugin....

**Comment by BajanVlogs** [comment]
Clearly you don't know CortexPE said I could take down this plugin

**Comment by BajanVlogs** [comment]
Also clearly if you used this on ur server people can grief your spawn as you don't have the edited spawn protection plugin

**Comment by StrafelessPvP** [comment]
Theres something called Iprotector ;)

**Comment by CortexPE** [comment]
oh hey my work has been stolen again. wow ***totally surprised***
[![wow](https://m.popkey.co/a500e7/qVJJ5.gif)](https://m.popkey.co/a500e7/qVJJ5.gif)

**Comment by CortexPE** [comment]
and no bajan, you don't have the right to take this down... I'm the copyright holder... not you.
stop claiming plugins you purchased as your own.

**Comment by BajanVlogs** [comment]
Tell him to take it down

**Comment by BajanVlogs** [comment]
Its honestly gay why they have to keep uploading it but this plugin won't even work in 1.3 anyways so Ill have a brand new one for 1.3

**Comment by CortexPE** [comment]
nah. you already leaked it. no point of taking these repos down. the damage has already been done.
ａｌｌ　ｂｅｃａｕｓｅ　ｏｆ　ｙｏｕ　ゖ欧ゼ哀

**Comment by BajanVlogs** [comment]
Well anyways Happy new year
